before_script:
  - mkdir -p ~/yocto-webkit
  - cd ~/yocto-webkit
  - ulimit -n 4096
  - repo init -u $CI_REPOSITORY_URL -m $MANIFEST -b $CI_COMMIT_SHA
  - repo sync --force-sync
  - pushd sources/meta-webkit
  - git remote remove tmp || true
  - git remote add tmp $CI_REPOSITORY_URL
  - git fetch tmp
  - git checkout $CI_COMMIT_SHA
  - popd
  - source sources/meta-webkit/.gitlab-ci/scripts/setup-environment $SOURCE
  - rm -rf tmp

dunfell-raspberrypi3-mesa-weston-wpe-2.28:
  tags:
    - meta-webkit
  variables:
    MANIFEST: .gitlab-ci/manifest/manifest-dunfell.xml
    # setup-environment targetname machine distro bblayers presets
    SOURCE: raspberrypi3-mesa-wpe-2.28 raspberrypi3-mesa poky raspberrypi mesa-wpe-2_28
    BITBAKE_TARGET: wpewebkit
  script:
    - bitbake $BITBAKE_TARGET
    - rm -rf tmp

dunfell-raspberrypi3-mesa-weston-wpe-2.30:
  tags:
    - meta-webkit
  variables:
    MANIFEST: .gitlab-ci/manifest/manifest-dunfell.xml
    # setup-environment targetname machine distro bblayers presets
    SOURCE: raspberrypi3-mesa-wpe-2.30 raspberrypi3-mesa poky raspberrypi mesa-wpe-2_30
    BITBAKE_TARGET: wpewebkit
  script:
    - bitbake $BITBAKE_TARGET
    - rm -rf tmp

dunfell-raspberrypi3-mesa-weston-wpe-2.32:
  tags:
    - meta-webkit
  variables:
    MANIFEST: .gitlab-ci/manifest/manifest-dunfell.xml
    # setup-environment targetname machine distro bblayers presets
    SOURCE: raspberrypi3-mesa-wpe-2.32 raspberrypi3-mesa poky raspberrypi mesa-wpe-2_32
    BITBAKE_TARGET: wpewebkit
  script:
    - bitbake $BITBAKE_TARGET
    - rm -rf tmp

dunfell-raspberrypi3-mesa-weston-wpe-qt:
  allow_failure: true
  tags:
    - meta-webkit
  variables:
    MANIFEST: .gitlab-ci/manifest/manifest-dunfell.xml
    # setup-environment targetname machine distro bblayers presets
    SOURCE: raspberrypi3-mesa-wpe-qt raspberrypi3-mesa poky qt5 mesa-wpe-qt
    BITBAKE_TARGET: wpewebkit
  script:
    - bitbake $BITBAKE_TARGET
    - rm -rf tmp
