name: 'Manual check for external Pull Requests'
on:
  workflow_dispatch:
    inputs:
      pr-id:
        description: 'Pull Request Id'
        required: true
        default: '0'
      target-branch:
        description: 'Target branch'
        required: true
        default: 'main'

jobs:
  check-external-pr:
    runs-on: ubuntu-latest
    name: Create an internal branch for check the MR into the CI
    env:
      BOT_USER: "meta-webkit bot"
      BOT_EMAIL: "meta-webkit@igalia.com"
      REPO: git@github.com:Igalia/meta-webkit.git
      MIRROR: git@gitlab.com:browsers/meta-webkit.git
    steps:
    - run: |
       # Set the $SSH_PRIVATE_KEY environment variable in the CI to the base64
       # encoded private key generated like this:
       #   ssh-keygen  -t ecdsa -f runner_ecdsa
       #   cat runner_ecdsa | base64 -w0
       echo "Creating branch for Pull request \#${{ github.event.inputs.pr-id }}"
       eval $(ssh-agent -s)
       (echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode | ssh-add -) || true
       mkdir -p ~/.ssh
       chmod 700 ~/.ssh
       ssh-keyscan -t rsa gitlab.com github.com >>~/.ssh/known_hosts
       git config --global user.name "${{ env.BOT_USER }}"
       git config --global user.email "${{ env.BOT_EMAIL }}"
       git config --global pull.rebase "preserve"
       git clone ${{ env.REPO }} repo
       cd repo
       git remote add gitlab ${{ env.MIRROR }}
       git fetch ${{ env.REPO }} pull/${{ github.event.inputs.pr-id }}/head:pull/${{ github.event.inputs.pr-id }}
       git checkout pull/${{ github.event.inputs.pr-id }}
       git push --force gitlab pull/${{ github.event.inputs.pr-id }}
       curl -X POST \
         -H "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
         "https://gitlab.com/api/v4/projects/browsers%2Fmeta-webkit/mirror/pull"
       curl -X POST \
         -H "Accept: application/vnd.github.v3+json" \
         -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
         "https://api.github.com/repos/Igalia/meta-webkit/issues/${{ github.event.inputs.pr-id }}/comments" \
         -d '{"body":"Pull Request is being checked for https://github.com/Igalia/meta-webkit/pull/${{ github.event.inputs.pr-id }}/commits"}'
